# Generated by Django 3.0 on 2020-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webregister',
            name='end_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
