# Generated by Django 3.0 on 2020-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregisterationuser',
            name='header_eventimage',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
