# Generated by Django 3.0 on 2020-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200810_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregisterationuser',
            name='footer_eventimage',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='eventregisterationuser',
            name='streaming_header',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='eventregisterationuser',
            name='streaming_leftpanel',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='eventregisterationuser',
            name='streaming_rightpanel',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
